-- Creacion de tablas

CREATE TABLE Usuario(
	correo VARCHAR(15)  PRIMARY KEY,
	username VARCHAR(15),
	contrasenia VARCHAR(10),
	pais VARCHAR(10),
	fecha_creacion DATE,
	tipo_suscripcion BOOLEAN
);

CREATE TABLE Playlist(
	ID INT PRIMARY KEY,
	correo_usuario  VARCHAR(15) FOREIGN KEY REFERENCES Usuario(correo),
	fecha_creacion DATE,
	privacidad BOOLEAN,
	nombre  VARCHAR(15),
	descripcion  VARCHAR(40)
);

CREATE TABLE Contenido(
	ID INT PRIMARY KEY,
	fechaLanzamiento DATE,
	lenguaje VARCHAR(10),
	nombre VARCHAR(15),
);

CREATE TABLE ArtistaMusical(
	correo_usuario  VARCHAR(15) FOREIGN KEY REFERENCES Usuario(correo),
	genero_musica VARCHAR(10)
);

CREATE TABLE RedSocial(
	nombre VARCHAR(15) PRIMARY KEY
);

CREATE TABLE Evento(
	nombre VARCHAR(15) PRIMARY KEY,
	fecha DATE,
	lugar VARCHAR(15)
);

CREATE TABLE ArtistaPodcast(
	correo_usuario VARCHAR(15) FOREIGN KEY REFERENCES Usuario(correo)
);


CREATE TABLE ContenidoAcumulable(
	ID INT FOREIGN KEY REFERENCES Contenido(ID),
	duracion TIME
);

CREATE TABLE Podcast(
	nombre VARCHAR(15) PRIMARY KEY,
	original BOOLEAN
);

CREATE TABLE Album(
	ID INT FOREIGN KEY REFERENCES Contenido(ID)
);

CREATE TABLE Episodio(
	ID INT FOREIGN KEY REFERENCES Contenido(ID),
	nombre VARCHAR(15) FOREIGN KEY REFERENCES Podcast(nombre),
	temporada VARCHAR(15)
);

CREATE TABLE Cancion(
	ID INT FOREIGN KEY REFERENCES Contenido(ID),
	genero  VARCHAR(10),
	compositor  VARCHAR(15)
);

CREATE TABLE Favoritos(
	correo VARCHAR(15) FOREIGN KEY REFERENCES Usuario(correo),
	ID INT FOREIGN KEY REFERENCES ContenidoAcumulable(ID)
);

CREATE TABLE AlmacenaPlaylist(
	IDplaylist INT FOREIGN KEY REFERENCES Playlist(ID),
	correo VARCHAR(15) FOREIGN KEY REFERENCES Usuario(correo),
	ID_CA INT FOREIGN KEY REFERENCES ContenidoAcumulable(ID)
);

CREATE TABLE Participa(
	correo VARCHAR(15) FOREIGN KEY REFERENCES ArtistaPodcast(correo_usuario),
	nombre VARCHAR(15)  FOREING KEY REFERENCES Podcast(Nombre)
);


CREATE TABLE TieneRedes(
	correo VARCHAR(15) FOREIGN KEY REFERENCES ArtistaPodcast(correo_usuario),
	nombre_Red VARCHAR(10) FOREIGN KEY REFERENCES RedSocial(nombre),
	username VARCHAR(10)
);

CREATE TABLE TieneEventos(
	correo VARCHAR(15) FOREIGN KEY REFERENCES ArtistaPodcast(correo_usuario),
	nombre VARCHAR(15) FOREIGN KEY REFERENCES Evento(nombre)
);

CREATE TABLE AlmacenaAlbum(
	ID_Cn INT FOREIGN KEY REFERENCES Cancion(ID),
	ID_Ab INT FOREIGN KEY REFERENCES Album(ID)
);

CREATE TABLE CreaAlbum(
	correo VARCHAR(15) FOREIGN KEY REFERENCES ArtistaMusical(correo),
	ID_Ab INT FOREIGN KEY REFERENCES Album(ID)
);

CREATE TABLE CreaCancion(
	correo VARCHAR(15) FOREIGN KEY REFERENCES ArtistaMusical(correo),
	ID_Cn INT FOREIGN KEY REFERENCES Cancion(ID)
);

CREATE TABLE CreaEpisodio(
	nombre VARCHAR(15) FOREIGN KEY REFERENCES Podcast(Nombre),
	ID_Ep INT FOREIGN KEY REFERENCES Episodio(ID)
);


ALTER TABLE Usuario MODIFY COLUMN ID NOT NULL;
ALTER TABLE Playlist MODIFY COLUMN ID NOT NULL;
ALTER TABLE Contenido MODIFY COLUMN ID NOT NULL;
ALTER TABLE ArtistaMusical MODIFY COLUMN ID NOT NULL;
ALTER TABLE RedSocial MODIFY COLUMN nombre NOT NULL;
ALTER TABLE Evento MODIFY COLUMN nombre NOT NULL;
ALTER TABLE ArtistaPodcast MODIFY COLUMN ID NOT NULL;
ALTER TABLE ContenidoAcumulable MODIFY COLUMN ID NOT NULL;
ALTER TABLE Podcast MODIFY COLUMN nombre NOT NULL;
ALTER TABLE Album MODIFY COLUMN ID NOT NULL;
ALTER TABLE Episodio MODIFY COLUMN ID NOT NULL;
ALTER TABLE Cancion MODIFY COLUMN ID NOT NULL;
ALTER TABLE Favoritos MODIFY COLUMN ID NOT NULL;
ALTER TABLE AlmacenaPlaylist MODIFY COLUMN IDplaylist NOT NULL;
ALTER TABLE Participa MODIFY COLUMN nombre NOT NULL;
ALTER TABLE TieneRedes MODIFY COLUMN nombre_Red NOT NULL;
ALTER TABLE TieneEventos MODIFY COLUMN nombre NOT NULL;
ALTER TABLE AlmacenaAlbum MODIFY COLUMN ID_Cn NOT NULL;
ALTER TABLE CreaAlbum MODIFY COLUMN ID_Ab NOT NULL;
ALTER TABLE CreaCancion MODIFY COLUMN ID_Cn NOT NULL;
ALTER TABLE CreaEpisodio MODIFY COLUMN ID_Ep NOT NULL;
